// Mock data for micro-adventures activities

export const activityCategories = [
  { id: 'all', name: 'All Activities', icon: 'Grid3x3', count: 50 },
  { id: 'arts', name: 'Creative Arts', icon: 'Palette', count: 15, color: 'from-purple-500 to-pink-500' },
  { id: 'reading', name: 'Reading & Language', icon: 'BookOpen', count: 12, color: 'from-blue-500 to-cyan-500' },
  { id: 'stem', name: 'STEM & Science', icon: 'FlaskConical', count: 13, color: 'from-green-500 to-emerald-500' },
  { id: 'active', name: 'Active & Outdoor', icon: 'TreePine', count: 11, color: 'from-orange-500 to-amber-500' },
  { id: 'cultural', name: 'Cultural & Heritage', icon: 'Globe', count: 9, color: 'from-rose-500 to-red-500' },
  { id: 'logic', name: 'Problem Solving', icon: 'Puzzle', count: 8, color: 'from-indigo-500 to-purple-500' },
  { id: 'music', name: 'Music & Movement', icon: 'Music', count: 7, color: 'from-pink-500 to-rose-500' },
  { id: 'cooking', name: 'Cooking & Life Skills', icon: 'ChefHat', count: 8, color: 'from-yellow-500 to-orange-500' }
];

export const mockActivities = [
  // STEM & Science
  {
    id: '1',
    title: 'Volcano Eruption',
    category: 'stem',
    description: 'Create a baking soda and vinegar volcano. Learn about chemical reactions through exciting eruptions!',
    fullDescription: 'Build an erupting volcano using household materials and learn about chemical reactions, geology, and the scientific method. Kids will mix baking soda and vinegar to create a fizzing eruption while learning why it happens.',
    ageRange: '4-10 years',
    ageMin: 4,
    ageMax: 10,
    duration: '30-45 min',
    difficulty: 'Beginner',
    learningGoals: ['Scientific reasoning', 'Cause and effect', 'Fine motor skills', 'Following instructions'],
    materials: ['Baking soda', 'Vinegar', 'Food coloring', 'Plastic bottle', 'Clay or playdough'],
    messLevel: 'Medium',
    popularity: 47,
    indoor: true,
    outdoor: false
  },
  {
    id: '2',
    title: 'Rainbow STEM Challenge',
    category: 'stem',
    description: 'Build structures using only colored materials. Combine engineering with color theory in this creative challenge.',
    fullDescription: 'Design and build structures using materials of specific colors, teaching color recognition, engineering principles, and problem-solving. Each color has different properties (flexible, rigid, etc.)',
    ageRange: '5-12 years',
    ageMin: 5,
    ageMax: 12,
    duration: '45-60 min',
    difficulty: 'Intermediate',
    learningGoals: ['Engineering basics', 'Color theory', 'Problem solving', 'Creative thinking'],
    materials: ['Colored paper', 'Pipe cleaners', 'Popsicle sticks', 'Tape', 'Building blocks'],
    messLevel: 'Low',
    popularity: 32,
    indoor: true,
    outdoor: false
  },
  {
    id: '3',
    title: 'Kitchen Science Lab',
    category: 'stem',
    description: 'Turn the kitchen into a science lab with safe, edible experiments. Make slime, crystals, and more!',
    fullDescription: 'Conduct safe kitchen science experiments using food items. Make rock candy crystals, create edible slime with cornstarch, and explore density with oil and water.',
    ageRange: '6-12 years',
    ageMin: 6,
    ageMax: 12,
    duration: '40-50 min',
    difficulty: 'Intermediate',
    learningGoals: ['Scientific method', 'Observation skills', 'States of matter', 'Measurement'],
    materials: ['Sugar', 'Water', 'Cornstarch', 'Food coloring', 'Oil', 'Measuring cups'],
    messLevel: 'Medium',
    popularity: 38,
    indoor: true,
    outdoor: false
  },

  // Reading & Language
  {
    id: '4',
    title: 'Bilingual Storytime',
    category: 'reading',
    description: 'Read classic stories in native language, then discuss in English. Maintain mother tongue while building English skills.',
    fullDescription: 'Foster bilingual development by reading culturally relevant stories in the child\'s heritage language, then discussing themes, characters, and lessons in English. Strengthens both languages while building cultural pride.',
    ageRange: '2-8 years',
    ageMin: 2,
    ageMax: 8,
    duration: '20-30 min',
    difficulty: 'Beginner',
    learningGoals: ['Bilingualism', 'Listening comprehension', 'Cultural connection', 'Vocabulary'],
    materials: ['Books in heritage language', 'Comfortable reading space'],
    messLevel: 'Low',
    popularity: 56,
    indoor: true,
    outdoor: false,
    specialFeature: 'Available in 15+ languages'
  },
  {
    id: '5',
    title: 'Create Your Own Story',
    category: 'reading',
    description: 'Write and illustrate an original story together. Develop writing skills, sequencing, and creativity.',
    fullDescription: 'Guide children through the story creation process from brainstorming characters to illustrating their masterpiece. Learn story structure, character development, and narrative arc.',
    ageRange: '5-12 years',
    ageMin: 5,
    ageMax: 12,
    duration: '45-60 min',
    difficulty: 'Intermediate',
    learningGoals: ['Creative writing', 'Sequencing', 'Illustration', 'Narrative structure'],
    materials: ['Paper', 'Pencils', 'Crayons or markers', 'Stapler for binding'],
    messLevel: 'Low',
    popularity: 41,
    indoor: true,
    outdoor: false
  },
  {
    id: '6',
    title: 'Poetry Workshop',
    category: 'reading',
    description: 'Experiment with haiku, acrostic, and rhyming poems. Express feelings through poetic language.',
    fullDescription: 'Explore different poetry forms while learning about rhythm, rhyme, and creative expression. Children create multiple poems and compile them into a personal poetry book.',
    ageRange: '7-12 years',
    ageMin: 7,
    ageMax: 12,
    duration: '35-45 min',
    difficulty: 'Intermediate',
    learningGoals: ['Creative writing', 'Rhythm and rhyme', 'Self-expression', 'Literary forms'],
    materials: ['Paper', 'Pencils', 'Optional: decorative supplies'],
    messLevel: 'Low',
    popularity: 28,
    indoor: true,
    outdoor: false
  },

  // Creative Arts
  {
    id: '7',
    title: 'Nature Collage Creation',
    category: 'arts',
    description: 'Collect natural materials and create beautiful collages. Learn about textures, colors, and patterns in nature.',
    fullDescription: 'Take a nature walk to collect leaves, flowers, twigs, and pebbles, then arrange them into artistic collages. Discuss textures, patterns, and the science of nature while creating art.',
    ageRange: '3-8 years',
    ageMin: 3,
    ageMax: 8,
    duration: '30-45 min',
    difficulty: 'Beginner',
    learningGoals: ['Fine motor skills', 'Nature appreciation', 'Pattern recognition', 'Creative expression'],
    materials: ['Paper', 'Glue', 'Natural materials', 'Optional: crayons for leaf rubbings'],
    messLevel: 'Medium',
    popularity: 52,
    indoor: false,
    outdoor: true
  },
  {
    id: '8',
    title: 'Cultural Art Traditions',
    category: 'arts',
    description: 'Explore art from your family\'s culture—paper cutting, rangoli patterns, mask-making, or geometric designs.',
    fullDescription: 'Connect with heritage through traditional art forms. Choose from Chinese paper cutting, Indian rangoli, African masks, Islamic geometry, or other cultural traditions.',
    ageRange: '5-12 years',
    ageMin: 5,
    ageMax: 12,
    duration: '45-60 min',
    difficulty: 'Intermediate',
    learningGoals: ['Cultural identity', 'Fine motor skills', 'Historical awareness', 'Pattern recognition'],
    materials: ['Varies by tradition: paper, colored powder/sand, cardboard, paint'],
    messLevel: 'Medium',
    popularity: 44,
    indoor: true,
    outdoor: false,
    specialFeature: 'Customizable to family heritage'
  },
  {
    id: '9',
    title: 'Recycled Art Sculpture',
    category: 'arts',
    description: 'Transform recyclables into imaginative sculptures. Learn environmental responsibility through creativity.',
    fullDescription: 'Build robots, animals, or abstract sculptures from cardboard boxes, bottles, and packaging. Teaches environmental awareness, 3D thinking, and resourcefulness.',
    ageRange: '4-10 years',
    ageMin: 4,
    ageMax: 10,
    duration: '45-60 min',
    difficulty: 'Intermediate',
    learningGoals: ['Environmental awareness', '3D thinking', 'Resourcefulness', 'Engineering basics'],
    materials: ['Recyclables (boxes, bottles, egg cartons)', 'Tape', 'Glue', 'Paint (optional)'],
    messLevel: 'Medium',
    popularity: 35,
    indoor: true,
    outdoor: false
  },

  // Active & Outdoor
  {
    id: '10',
    title: 'Nature Scavenger Hunt',
    category: 'active',
    description: 'Follow clues to find natural items. Explore the outdoors while learning about local ecology.',
    fullDescription: 'Hunt for specific leaves, rocks, colors, and textures in nature. Learn plant identification, animal tracking signs, and ecological concepts through active exploration.',
    ageRange: '3-10 years',
    ageMin: 3,
    ageMax: 10,
    duration: '30-45 min',
    difficulty: 'Beginner',
    learningGoals: ['Nature observation', 'Physical activity', 'Following directions', 'Ecology basics'],
    materials: ['Scavenger hunt list', 'Collection bag', 'Outdoor space'],
    messLevel: 'Low',
    popularity: 64,
    indoor: false,
    outdoor: true
  },
  {
    id: '11',
    title: 'Obstacle Course Challenge',
    category: 'active',
    description: 'Design and complete a custom obstacle course. Build gross motor skills and problem-solving.',
    fullDescription: 'Children help design an obstacle course using household items or outdoor features, then time themselves completing it. Teaches planning, physical coordination, and personal achievement.',
    ageRange: '4-12 years',
    ageMin: 4,
    ageMax: 12,
    duration: '30-45 min',
    difficulty: 'Beginner',
    learningGoals: ['Gross motor skills', 'Planning', 'Physical fitness', 'Goal setting'],
    materials: ['Household items for obstacles (cushions, boxes, rope)', 'Timer'],
    messLevel: 'Low',
    popularity: 58,
    indoor: true,
    outdoor: true
  },
  {
    id: '12',
    title: 'Yoga & Mindfulness',
    category: 'active',
    description: 'Fun yoga poses and breathing exercises for kids. Learn body awareness and emotional regulation.',
    fullDescription: 'Practice child-friendly yoga poses with creative names (tree, cat, warrior), combined with breathing exercises and mindfulness activities to support emotional regulation.',
    ageRange: '3-10 years',
    ageMin: 3,
    ageMax: 10,
    duration: '20-30 min',
    difficulty: 'Beginner',
    learningGoals: ['Body awareness', 'Emotional regulation', 'Flexibility', 'Mindfulness'],
    materials: ['Yoga mat or soft surface', 'Quiet space'],
    messLevel: 'Low',
    popularity: 39,
    indoor: true,
    outdoor: true,
    specialFeature: 'Excellent for calming and transitions'
  },

  // Cultural & Heritage
  {
    id: '13',
    title: 'Cultural Cooking Together',
    category: 'cultural',
    description: 'Make traditional dishes from your heritage. Learn about culture through food, measurements, and traditions.',
    fullDescription: 'Prepare simple cultural dishes (dumplings, chapati, empanadas, etc.) while learning about family traditions, measurements, following recipes, and cultural stories.',
    ageRange: '5-12 years',
    ageMin: 5,
    ageMax: 12,
    duration: '45-60 min',
    difficulty: 'Intermediate',
    learningGoals: ['Cultural identity', 'Following recipes', 'Measurements', 'Life skills'],
    materials: ['Recipe ingredients', 'Cooking utensils', 'Parent approval for kitchen use'],
    messLevel: 'High',
    popularity: 48,
    indoor: true,
    outdoor: false,
    specialFeature: 'Customizable to any culture'
  },
  {
    id: '14',
    title: 'World Music Exploration',
    category: 'cultural',
    description: 'Listen to music from different cultures, learn simple instruments, and explore rhythms from around the world.',
    fullDescription: 'Explore musical traditions from various cultures using recordings, simple instruments, and rhythm games. Learn about musical diversity and cultural expression.',
    ageRange: '3-10 years',
    ageMin: 3,
    ageMax: 10,
    duration: '25-35 min',
    difficulty: 'Beginner',
    learningGoals: ['Cultural awareness', 'Rhythm and music', 'Listening skills', 'Movement'],
    materials: ['Music player', 'Simple instruments or homemade shakers', 'Scarves for dancing'],
    messLevel: 'Low',
    popularity: 31,
    indoor: true,
    outdoor: false
  },
  {
    id: '15',
    title: 'Heritage Stories & Legends',
    category: 'cultural',
    description: 'Share folktales and legends from your family\'s culture. Connect with traditions through storytelling.',
    fullDescription: 'Read or tell traditional stories, myths, and legends from the child\'s cultural background. Discuss themes, morals, and cultural values while building identity and pride.',
    ageRange: '4-12 years',
    ageMin: 4,
    ageMax: 12,
    duration: '20-30 min',
    difficulty: 'Beginner',
    learningGoals: ['Cultural identity', 'Listening comprehension', 'Moral reasoning', 'Heritage connection'],
    materials: ['Cultural storybooks or oral traditions', 'Comfortable seating'],
    messLevel: 'Low',
    popularity: 42,
    indoor: true,
    outdoor: false
  },

  // Music & Movement
  {
    id: '16',
    title: 'Dance Party Freeze Game',
    category: 'music',
    description: 'Dance to various music styles, freezing when music stops. Build rhythm, listening skills, and self-control.',
    fullDescription: 'Play music from different genres and cultures. When music stops, children freeze in creative poses. Develops listening skills, self-regulation, and cultural music appreciation.',
    ageRange: '2-8 years',
    ageMin: 2,
    ageMax: 8,
    duration: '15-25 min',
    difficulty: 'Beginner',
    learningGoals: ['Self-regulation', 'Listening skills', 'Gross motor skills', 'Cultural music'],
    materials: ['Music player', 'Open space for dancing'],
    messLevel: 'Low',
    popularity: 67,
    indoor: true,
    outdoor: true
  },
  {
    id: '17',
    title: 'Homemade Instrument Band',
    category: 'music',
    description: 'Create instruments from household items and perform a concert. Learn about sound, rhythm, and creativity.',
    fullDescription: 'Build shakers, drums, guitars, and other instruments from recyclables and household items. Learn about sound production, pitch, and rhythm while fostering creativity.',
    ageRange: '4-10 years',
    ageMin: 4,
    ageMax: 10,
    duration: '40-50 min',
    difficulty: 'Intermediate',
    learningGoals: ['Sound science', 'Creativity', 'Fine motor skills', 'Rhythm'],
    materials: ['Recyclables (boxes, bottles)', 'Rice/beans', 'Rubber bands', 'Paper towel tubes'],
    messLevel: 'Medium',
    popularity: 45,
    indoor: true,
    outdoor: false
  },

  // Problem Solving & Logic
  {
    id: '18',
    title: 'Puzzle Design Challenge',
    category: 'logic',
    description: 'Create custom puzzles for others to solve. Develop logical thinking and spatial reasoning.',
    fullDescription: 'Design and create various types of puzzles: jigsaw, maze, riddles, or logic puzzles. Then challenge family members to solve them.',
    ageRange: '6-12 years',
    ageMin: 6,
    ageMax: 12,
    duration: '35-45 min',
    difficulty: 'Intermediate',
    learningGoals: ['Logical thinking', 'Spatial reasoning', 'Problem solving', 'Creativity'],
    materials: ['Paper', 'Pencils', 'Scissors', 'Cardboard (for jigsaw)'],
    messLevel: 'Low',
    popularity: 29,
    indoor: true,
    outdoor: false
  },
  {
    id: '19',
    title: 'Coding with No Screens',
    category: 'logic',
    description: 'Learn coding concepts through physical activities. Build computational thinking without technology.',
    fullDescription: 'Use cards, floor grids, and movement to teach programming concepts like sequencing, loops, and conditionals. Foundation for future coding skills.',
    ageRange: '5-10 years',
    ageMin: 5,
    ageMax: 10,
    duration: '30-40 min',
    difficulty: 'Intermediate',
    learningGoals: ['Computational thinking', 'Sequencing', 'Problem solving', 'Following algorithms'],
    materials: ['Direction cards', 'Grid markings (tape on floor)', 'Objects to collect'],
    messLevel: 'Low',
    popularity: 36,
    indoor: true,
    outdoor: true
  },

  // Cooking & Life Skills
  {
    id: '20',
    title: 'Healthy Snack Chef',
    category: 'cooking',
    description: 'Prepare nutritious snacks together. Learn about nutrition, measurements, and kitchen safety.',
    fullDescription: 'Make simple, healthy snacks like fruit kabobs, veggie faces, or energy balls. Discuss nutrition, practice measuring, and learn safe kitchen practices.',
    ageRange: '4-10 years',
    ageMin: 4,
    ageMax: 10,
    duration: '25-35 min',
    difficulty: 'Beginner',
    learningGoals: ['Nutrition awareness', 'Measurements', 'Kitchen safety', 'Following directions'],
    materials: ['Fruits/vegetables', 'Measuring cups', 'Child-safe utensils', 'Plates'],
    messLevel: 'Medium',
    popularity: 53,
    indoor: true,
    outdoor: false
  },
  {
    id: '21',
    title: 'Money & Math Market',
    category: 'cooking',
    description: 'Set up a pretend store and practice money skills. Learn about currency, addition, and economics.',
    fullDescription: 'Create a home store with real or play items, price tags, and play money. Practice making change, addition, and basic economic concepts through play.',
    ageRange: '5-10 years',
    ageMin: 5,
    ageMax: 10,
    duration: '30-40 min',
    difficulty: 'Intermediate',
    learningGoals: ['Math skills', 'Money concepts', 'Addition/subtraction', 'Real-world application'],
    materials: ['Household items to "sell"', 'Play money or real coins', 'Price tags', 'Shopping bag'],
    messLevel: 'Low',
    popularity: 37,
    indoor: true,
    outdoor: false
  }
];

// Helper functions
export function getActivitiesByCategory(categoryId) {
  if (categoryId === 'all') return mockActivities;
  return mockActivities.filter(activity => activity.category === categoryId);
}

export function getActivitiesByAge(age) {
  return mockActivities.filter(activity => age >= activity.ageMin && age <= activity.ageMax);
}

export function searchActivities(query) {
  const lowerQuery = query.toLowerCase();
  return mockActivities.filter(activity => 
    activity.title.toLowerCase().includes(lowerQuery) ||
    activity.description.toLowerCase().includes(lowerQuery) ||
    activity.learningGoals.some(goal => goal.toLowerCase().includes(lowerQuery))
  );
}
