export const adventures = [
  {
    id: "1",
    title: "Nature Explorer",
    description:
      "Discover the wonders of nature through outdoor exploration, bug hunts, and nature crafts",
    category: "Outdoor",
    ageRange: "3-8 years",
    duration: "2 hours",
    price: 35,
    difficulty: "Easy",
    image: "nature",
    activities: [
      "Nature scavenger hunt",
      "Leaf and flower collection",
      "Bug observation",
      "Nature journaling",
      "Outdoor art with natural materials",
    ],
    materials: [
      "Magnifying glass",
      "Collection bags",
      "Nature journal",
      "Crayons",
    ],
    learningGoals: [
      "Environmental awareness",
      "Observation skills",
      "Outdoor safety",
    ],
    sitterId: "1",
  },
  {
    id: "2",
    title: "Little Chef",
    description:
      "Learn basic cooking skills while making healthy and fun snacks together",
    category: "Culinary",
    ageRange: "4-10 years",
    duration: "1.5 hours",
    price: 40,
    difficulty: "Medium",
    image: "cooking",
    activities: [
      "Fruit kabobs creation",
      "Pizza making",
      "Cookie decorating",
      "Smoothie blending",
      "Kitchen safety basics",
    ],
    materials: [
      "Child-safe utensils",
      "Aprons",
      "Fresh ingredients",
      "Measuring cups",
    ],
    learningGoals: [
      "Cooking basics",
      "Healthy eating",
      "Following instructions",
      "Kitchen safety",
    ],
    sitterId: "1",
  },
  {
    id: "3",
    title: "Art Studio",
    description:
      "Express creativity through painting, drawing, and mixed media art projects",
    category: "Arts & Crafts",
    ageRange: "3-12 years",
    duration: "2 hours",
    price: 35,
    difficulty: "Easy",
    image: "art",
    activities: [
      "Watercolor painting",
      "Collage making",
      "Clay sculpting",
      "Drawing lessons",
      "Mixed media projects",
    ],
    materials: ["Paints", "Brushes", "Paper", "Clay", "Craft supplies"],
    learningGoals: [
      "Creative expression",
      "Fine motor skills",
      "Color theory",
      "Art appreciation",
    ],
    sitterId: "1",
  },
  {
    id: "4",
    title: "Sports Challenge",
    description: "Stay active with fun sports activities and team games",
    category: "Physical Activity",
    ageRange: "5-12 years",
    duration: "2 hours",
    price: 40,
    difficulty: "Medium",
    image: "sports",
    activities: [
      "Soccer drills",
      "Basketball skills",
      "Relay races",
      "Team building games",
      "Stretching and warm-up",
    ],
    materials: ["Sports balls", "Cones", "Water bottles", "First aid kit"],
    learningGoals: [
      "Physical fitness",
      "Teamwork",
      "Sportsmanship",
      "Coordination",
    ],
    sitterId: "2",
  },
  {
    id: "5",
    title: "Water Fun",
    description: "Enjoy safe water activities and swimming games",
    category: "Outdoor",
    ageRange: "4-10 years",
    duration: "2 hours",
    price: 45,
    difficulty: "Medium",
    image: "swimming",
    activities: [
      "Swimming games",
      "Water safety practice",
      "Pool noodle races",
      "Diving practice",
      "Water aerobics for kids",
    ],
    materials: ["Swimwear", "Floaties", "Pool toys", "Towels", "Sunscreen"],
    learningGoals: [
      "Swimming skills",
      "Water safety",
      "Confidence building",
      "Physical fitness",
    ],
    sitterId: "2",
  },
  {
    id: "6",
    title: "Montessori Activities",
    description:
      "Engage in hands-on Montessori learning activities for independent exploration",
    category: "Educational",
    ageRange: "2-6 years",
    duration: "1.5 hours",
    price: 30,
    difficulty: "Easy",
    image: "montessori",
    activities: [
      "Practical life exercises",
      "Sensorial activities",
      "Language development",
      "Math manipulatives",
      "Cultural studies",
    ],
    materials: [
      "Montessori materials",
      "Trays",
      "Natural objects",
      "Learning cards",
    ],
    learningGoals: [
      "Independence",
      "Fine motor skills",
      "Concentration",
      "Problem-solving",
    ],
    sitterId: "3",
  },
  {
    id: "7",
    title: "Music & Movement",
    description: "Explore rhythm, dance, and musical instruments",
    category: "Arts & Crafts",
    ageRange: "2-8 years",
    duration: "1 hour",
    price: 20,
    difficulty: "Easy",
    image: "music",
    activities: [
      "Rhythm games",
      "Instrument exploration",
      "Dance party",
      "Song learning",
      "Musical storytelling",
    ],
    materials: [
      "Simple instruments",
      "Music player",
      "Scarves",
      "Rhythm sticks",
    ],
    learningGoals: [
      "Musical awareness",
      "Rhythm",
      "Coordination",
      "Self-expression",
    ],
    sitterId: "3",
  },
  {
    id: "8",
    title: "Bilingual Storytime",
    description:
      "Immersive language learning through stories and songs in Spanish and English",
    category: "Educational",
    ageRange: "2-7 years",
    duration: "1 hour",
    price: 25,
    difficulty: "Easy",
    image: "reading",
    activities: [
      "Bilingual stories",
      "Spanish songs",
      "Vocabulary games",
      "Picture books",
      "Puppet shows",
    ],
    materials: ["Bilingual books", "Puppets", "Flashcards", "Music"],
    learningGoals: [
      "Language development",
      "Cultural awareness",
      "Listening skills",
      "Vocabulary",
    ],
    sitterId: "4",
  },
  {
    id: "9",
    title: "Science Lab",
    description: "Conduct safe and exciting science experiments",
    category: "STEM",
    ageRange: "5-12 years",
    duration: "2 hours",
    price: 45,
    difficulty: "Medium",
    image: "science",
    activities: [
      "Chemistry experiments",
      "Physics demonstrations",
      "Biology observations",
      "Scientific method practice",
      "Hypothesis testing",
    ],
    materials: [
      "Safe chemicals",
      "Lab equipment",
      "Safety goggles",
      "Science journal",
    ],
    learningGoals: [
      "Scientific thinking",
      "Observation",
      "Critical thinking",
      "Safety awareness",
    ],
    sitterId: "5",
  },
  {
    id: "10",
    title: "Building & Engineering",
    description:
      "Create amazing structures and learn basic engineering concepts",
    category: "STEM",
    ageRange: "4-10 years",
    duration: "1.5 hours",
    price: 38,
    difficulty: "Medium",
    image: "building",
    activities: [
      "LEGO challenges",
      "Bridge building",
      "Simple machines",
      "Robotics basics",
      "Design thinking",
    ],
    materials: [
      "LEGO sets",
      "Building blocks",
      "Craft materials",
      "Simple tools",
    ],
    learningGoals: [
      "Engineering concepts",
      "Problem-solving",
      "Creativity",
      "Spatial reasoning",
    ],
    sitterId: "5",
  },
  {
    id: "11",
    title: "Sensory Play",
    description: "Calming sensory activities designed for all abilities",
    category: "Special Needs",
    ageRange: "2-10 years",
    duration: "1 hour",
    price: 22,
    difficulty: "Easy",
    image: "sensory",
    activities: [
      "Sensory bins",
      "Tactile exploration",
      "Calming activities",
      "Visual stimulation",
      "Sound exploration",
    ],
    materials: [
      "Sensory materials",
      "Fidget tools",
      "Textured objects",
      "Soft lighting",
    ],
    learningGoals: [
      "Sensory regulation",
      "Exploration",
      "Calm focus",
      "Self-awareness",
    ],
    sitterId: "6",
  },
  {
    id: "12",
    title: "Adventure Hike",
    description:
      "Explore local trails with fun hiking games and nature challenges",
    category: "Outdoor",
    ageRange: "6-12 years",
    duration: "3 hours",
    price: 60,
    difficulty: "Hard",
    image: "hiking",
    activities: [
      "Trail hiking",
      "Navigation basics",
      "Wildlife spotting",
      "Outdoor survival skills",
      "Photography walk",
    ],
    materials: ["Backpacks", "Water bottles", "Snacks", "First aid kit", "Map"],
    learningGoals: [
      "Physical endurance",
      "Nature appreciation",
      "Navigation",
      "Outdoor safety",
    ],
    sitterId: "8",
  },
];
